"use client";

import { useId, useState } from "react";
import { Sparkles } from "lucide-react";
import { apiJson, ApiError } from "@/lib/api";
import type { AiAction } from "@/lib/types";

type Provenance =
  | { status: "idle" | "loading" }
  | { status: "ready"; action: AiAction }
  | { status: "error"; message: string };

/**
 * "AI-generated · sources" label for generated content. With `aiActionId` it expands
 * to the provenance from GET /api/ai-actions/{id}; otherwise to `ran` (the tools and
 * agents that produced it), or to a note that no provenance record is available.
 */
export function AiGeneratedLabel({ aiActionId, ran = [] }: { aiActionId?: string | null; ran?: string[] }) {
  const [open, setOpen] = useState(false);
  const [provenance, setProvenance] = useState<Provenance>({ status: "idle" });
  const panelId = useId();

  const toggle = () => {
    const next = !open;
    setOpen(next);
    if (next && aiActionId && provenance.status !== "ready" && provenance.status !== "loading") {
      setProvenance({ status: "loading" });
      apiJson<AiAction>(`/api/ai-actions/${encodeURIComponent(aiActionId)}`, { reportForbidden: false })
        .then((action) => setProvenance({ status: "ready", action }))
        .catch((err: unknown) => {
          setProvenance({ status: "error", message: errorMessage(err) });
        });
    }
  };

  return (
    <div className="mt-1.5 text-[11px] text-gray-600" data-testid="ai-generated-label">
      <button
        type="button"
        onClick={toggle}
        aria-expanded={open}
        aria-controls={panelId}
        className="inline-flex items-center gap-1 rounded px-1 py-0.5 underline decoration-dotted underline-offset-2 hover:text-gray-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1a73e8]"
      >
        <Sparkles aria-hidden="true" className="h-3 w-3" />
        AI-generated · sources
      </button>
      {open && (
        <div id={panelId} className="mt-1 rounded border border-gray-200 bg-white p-2 text-gray-700">
          {aiActionId ? <ProvenanceDetail provenance={provenance} /> : <RanList ran={ran} />}
        </div>
      )}
    </div>
  );
}

function RanList({ ran }: { ran: string[] }) {
  if (ran.length === 0) return <p>Generated by the software. No provenance record is linked to this item.</p>;
  return (
    <>
      <p className="font-semibold">What ran</p>
      <ul className="list-disc pl-4">
        {ran.map((r) => <li key={r}>{r}</li>)}
      </ul>
    </>
  );
}

// The engine answers 404 both for a missing record and for one the viewer may not see yet,
// such as a learner's unreleased or rejected grade draft.
function errorMessage(err: unknown): string {
  if (err instanceof ApiError && err.status === 403) return "Your role can't view this provenance record.";
  if (err instanceof ApiError && err.status === 404) return "This provenance record isn't available to you.";
  return `Couldn't load sources: ${err instanceof Error ? err.message : String(err)}`;
}

function ProvenanceDetail({ provenance }: { provenance: Provenance }) {
  if (provenance.status === "error") return <p role="alert">{provenance.message}</p>;
  if (provenance.status !== "ready") return <p role="status">Loading sources…</p>;
  const a = provenance.action;
  return (
    <div className="space-y-1.5">
      <p>
        Generated by <span className="font-semibold">{a.agent}</span> ({a.action_type.replace(/_/g, " ")})
        {a.model ? <> with {a.model}</> : null} on {new Date(a.created_at).toLocaleString()}.
      </p>
      <div>
        <p className="font-semibold">Sources</p>
        {a.sources.length === 0 ? <p>None recorded.</p> : (
          <ul className="list-disc pl-4">
            {a.sources.map((s) => (
              <li key={`${s.type}:${s.id}`}>
                {s.title ?? s.id} <span className="text-gray-600">({s.type.replace(/_/g, " ")}{s.version != null ? `, v${s.version}` : ""})</span>
              </li>
            ))}
          </ul>
        )}
      </div>
      {a.policies.length > 0 && (
        <div>
          <p className="font-semibold">Policies applied</p>
          <ul className="list-disc pl-4">
            {a.policies.map((p) => (
              <li key={`${p.key}:${p.scope_type}`}>{p.key} = {JSON.stringify(p.value)} <span className="text-gray-600">({p.scope_type.replace(/_/g, " ")})</span></li>
            ))}
          </ul>
        </div>
      )}
      {a.decisions.length > 0 && (
        <div>
          <p className="font-semibold">Decisions</p>
          <ul className="list-disc pl-4">
            {a.decisions.map((d) => (
              <li key={d.id}>{d.decision} by {d.decided_by_name ?? "a person"} on {new Date(d.decided_at).toLocaleString()}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
