"use client";

import { useId, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { ApiError, apiJson } from "@/lib/api";
import { EMPTY_TURN_SOURCES, humanize, type AiAction, type TurnSources } from "@/lib/provenance";

/**
 * "AI-generated · sources" disclosure for generated content. Expanding it loads each
 * linked record from GET /api/ai-actions/{id}; with no ids it lists what the turn
 * reported (agents, tools, citations).
 */
export function AiGeneratedLabel({
  aiActionIds = [],
  sources = EMPTY_TURN_SOURCES,
}: {
  aiActionIds?: string[];
  sources?: TurnSources;
}) {
  const [open, setOpen] = useState(false);
  const panelId = useId();

  return (
    <div className="mt-2 text-[11px] text-foreground/80" data-testid="ai-generated-label">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        aria-controls={panelId}
        className="inline-flex items-center gap-1 rounded px-1 py-0.5 underline decoration-dotted underline-offset-2 hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
      >
        <Sparkles aria-hidden="true" className="h-3 w-3" />
        AI-generated · sources
      </button>
      {open && (
        <div
          id={panelId}
          className="mt-1 space-y-2 rounded border border-border bg-background p-2 text-foreground"
        >
          {aiActionIds.length > 0 ? (
            aiActionIds.map((id) => <ProvenanceRecord key={id} id={id} />)
          ) : (
            <TurnSourceList sources={sources} />
          )}
        </div>
      )}
    </div>
  );
}

function TurnSourceList({ sources }: { sources: TurnSources }) {
  const { agents, tools, citations } = sources;
  if (agents.length + tools.length + citations.length === 0) {
    return <p>Generated by the software. No provenance record is linked to this item.</p>;
  }
  return (
    <>
      <p>Generated by the software. No provenance record is linked to this item; this turn reported:</p>
      <SourceGroup heading="Agents" items={agents.map(humanize)} />
      <SourceGroup heading="Tools that ran" items={tools} />
      <SourceGroup heading="Cited sources" items={citations} />
    </>
  );
}

function SourceGroup({ heading, items }: { heading: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <div>
      <p className="font-semibold">{heading}</p>
      <ul className="list-disc pl-4">
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

function ProvenanceRecord({ id }: { id: string }) {
  const query = useQuery({
    queryKey: ["api", `/api/ai-actions/${id}`],
    queryFn: () => apiJson<AiAction>(`/api/ai-actions/${encodeURIComponent(id)}`),
    retry: false,
  });

  if (query.isPending) return <p role="status">Loading sources…</p>;
  if (query.isError) {
    const err = query.error;
    // 404 also covers a record the viewer may not see yet, such as a learner's unreleased draft.
    const message =
      err instanceof ApiError && err.status === 403
        ? "Your role can't view this provenance record."
        : err instanceof ApiError && err.status === 404
          ? "This provenance record isn't available to you."
          : "Couldn't load sources. Please try again.";
    return <p role="alert">{message}</p>;
  }

  const a = query.data;
  return (
    <div className="space-y-1.5">
      <p>
        Generated by <span className="font-semibold">{humanize(a.agent)}</span> ({humanize(a.action_type)})
        {a.model ? <> with {a.model}</> : null} on {new Date(a.created_at).toLocaleString()}.
      </p>
      <div>
        <p className="font-semibold">Sources</p>
        {a.sources.length === 0 ? (
          <p>None recorded.</p>
        ) : (
          <ul className="list-disc pl-4">
            {a.sources.map((s) => (
              <li key={`${s.type}:${s.id}`}>
                {s.title ?? s.id}{" "}
                <span className="text-muted-foreground">
                  ({humanize(s.type)}
                  {s.version != null ? `, version ${s.version}` : ""})
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>
      {a.policies.length > 0 && (
        <div>
          <p className="font-semibold">Policies applied</p>
          <ul className="list-disc pl-4">
            {a.policies.map((p) => (
              <li key={`${p.key}:${p.scope_type}:${p.scope_id ?? ""}`}>
                {p.key} = {JSON.stringify(p.value)}{" "}
                <span className="text-muted-foreground">({humanize(p.scope_type)})</span>
              </li>
            ))}
          </ul>
        </div>
      )}
      {a.decisions.length > 0 && (
        <div>
          <p className="font-semibold">Decisions</p>
          <ul className="list-disc pl-4">
            {a.decisions.map((d) => (
              <li key={d.id}>
                {d.decision} by {d.decided_by_name ?? "a person"} on{" "}
                {new Date(d.decided_at).toLocaleString()}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
